export { default as getMarkAttrs } from './utils/getMarkAttrs'
export { default as getMarkRange } from './utils/getMarkRange'
export { default as markIsActive } from './utils/markIsActive'
export { default as nodeEqualsType } from './utils/nodeEqualsType'
export { default as nodeIsActive } from './utils/nodeIsActive'
export { default as actorIsActive } from './utils/actorIsActive'
